project:
  type: book
  output-dir: docs

book:
  title: "AU Educational and Health Policy Research Center"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - research_projects.qmd
    - potential_funding_sources.qmd
    - someday_maybe.qmd  
    - training.qmd
    - outreach.qmd
    - PeerCenters.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



